campaign:
  storageSite: T2_CH_CERN
  outLFNDirBase: /store/group/phys_higgs/vbfhiggs
  tag_extension: NanoV12
  config: utils/nano_data_2022_FG_NANO.py
  data: True
  # datasets: /JetMET/Run2022F-22Sep2023-v2/MINIAOD #example to run on one sample only
  datasets: datasets/data_2022_FG.txt