campaign:
  storageSite: T2_CH_CERN
  outLFNDirBase: /store/group/phys_higgs/vbfhiggs
  tag_extension: NanoV12 # Will get appended after the current tag
  config: nano_mc_Run3_NANO.py
  # Specify if running on data
  # data: True
  data: False
  lumiMask: # json file TBA
  # datasets will take either a list of DAS names or a text file containing them
  #datasets: datasets/DoubleMuon_22.txt
  # do NOT submit too many tasks at the same time, despite it looking more convenient to you
  # wait for tasks to finish before submitting entire campaigns,
  # it's better to request one dataset at a time (taking fairshare into account)
  datasets: /VBFto2L_MLL-50_TuneCP5_13p6TeV_madgraph-pythia8/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v2/MINIAODSIM